server:
  port: 9099
knife4j:
  enableAggregation: true
  nacos:
    enable: true
    serviceUrl: http:/127.0.0.1:8848/nacos/
    routes:
      - name: 礼品平台
        serviceName: gift-baseinfo
        location: /v2/api-docs?group=default
        servicePath: /